### ISSUE TITLE
How to method call

### ISSUE THREAD

**Issue by aquari89** [FreeOpcUa/opcua-client-gui#17]
Hello, All.

I use the freeopcua Gui Client tool for the first time.
How do you call a method in this tool?

I do not know if there is no reference to the method call.

**Comment by oroulet** [comment]
no implemented.

**Comment by oroulet** [comment]
Implemented in master now

**Comment by fabian727** [comment]
Hi,

nice tool, works good but no "call method". Ive "installed"  the client again. It downloads the 0.7.2 official release version. Is it there already implemented? If so, where is the button (maybe I am too dump to see it)? If not, at which time will you release this version? If it is not tomorrow ;), how can I install your tool from this repo?

Thanks
Fabian

**Comment by oroulet** [comment]
Good point. Will release it ASAP

**Comment by oroulet** [comment]
Released need version now. Pip install opcua-client --upgrade

**Comment by oroulet** [comment]
Let me know if it work y

**Comment by fabian727** [comment]
thanks, if business world was as fast as you....
works like a charm.

I have methods with no return values at the moment. If I call them I get the response: 'NoneType' object is not iterable. Would be nice to get a feedback, like "method returned nothing, but calling worked". Your way I was at first glance not sure if it worked or it didn't, but it's a little feature-wish, no must have.

**Comment by oroulet** [comment]
Thanks for the feedback I will check that case

**Comment by zerox1212** [comment]
If you have control of the server it might be a good idea to have your methods at least return `success = 1`.

**Comment by oroulet** [comment]
@fabian727 can you open a new bug request and explain the issue again. put a screenshot of the method node and its children with their values. I did a few tests here and I did not get any errors

**Comment by fabian727** [comment]
those aren't errors. I think (didn't read your code) that you save the return values in an array and print all values and types, but if there is no feedback, I get this message

'NoneType' object is not iterable

So the call itself was successfull, but it is not stated because I do not return values and your gui only states there is no feedback
(@zerox1212 I do not want to return values, as it would be minimum a byte again, which crowds the network and yes this byte is important to me)

![screenshot from 2018-06-21 08-52-56](https://user-images.githubusercontent.com/11717140/41702481-928abb1a-7530-11e8-9e4e-5de497c175d4.png)

**Comment by oroulet** [comment]
That message is not normal. This is an error (but it may be a user error) what server do you use?

**Comment by oroulet** [comment]
I have had the same error earlier and this was user feil
